server.port=8081
spring.application.name=catalog-service

# ============ DB ============
# ?? ????????? ??? ?????????? ???????: Postgres ?? localhost:5434
spring.datasource.url=jdbc:postgresql://localhost:5434/catalog_db
spring.datasource.username=catalog_user
spring.datasource.password=catalog_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ============ JPA ============
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ============ Actuator ============
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never

# ============ Logging ============
logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
